### ISSUE TITLE
Node 16 x86 error at /canvas.node

### ISSUE THREAD

**Issue by elawad** [jwerre/node-canvas-lambda#18]
Hi, I've downloaded the latest x86 zip files from https://github.com/jwerre/node-canvas-lambda/releases/tag/v2.0.0
I then created two lambda layers, one for each zip file:

- node16_canvas_layer_x86_64.zip
- node16_canvas_lib64_layer_x86_64.zip

Then I attached both layers to my lambda function, and the function was built for x86 Node 16.
However after much research and attempts, I still get the error:
```
{
    "errorType": "Error",
    "errorMessage": "/opt/nodejs/node_modules/canvas/build/Release/canvas.node: cannot open shared object file: No such file or directory",
    "code": "ERR_DLOPEN_FAILED",
    "stack": [
        "Error: /opt/nodejs/node_modules/canvas/build/Release/canvas.node: cannot open shared object file: No such file or directory",
        "    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)",
        "    at Module.load (node:internal/modules/cjs/loader:981:32)",
        "    at Function.Module._load (node:internal/modules/cjs/loader:822:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1005:19)",
        "    at require (node:internal/modules/cjs/helpers:102:18)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/canvas/lib/bindings.js:3:18)",
        "    at Module._compile (node:internal/modules/cjs/loader:1105:14)",
        "    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)",
        "    at Module.load (node:internal/modules/cjs/loader:981:32)",
        "    at Function.Module._load (node:internal/modules/cjs/loader:822:12)"
    ]
}
```
The lambda function uses the following import:
`const { createCanvas, loadImage } = require('canvas');`

Any guidance would be much appreciated.

**Comment by elawad** [comment]
I was just able to test my lambda function using this layer instead:
https://github.com/charoitel/lambda-layer-canvas-nodejs/wiki/Getting-Started#deploy-through-aws-lambda-console

And that worked successfully. But hopefully this issue can be resolved.

**Comment by elawad** [comment]
Closing; I ended up using the above layer.

**Comment by Dartv** [comment]
Layers from https://github.com/charoitel/lambda-layer-canvas-nodejs work fine.
However, layers from this repo do not work and throw the same error `/opt/nodejs/node_modules/canvas/build/Release/canvas.node: cannot open shared object file: No such file or directory`
thus the issue should be reopened because this is the first repo you get when you search for canvas layers and people may get stuck if they don't look up closed issues...
