### ISSUE TITLE
Fontconfig error: Cannot load default config file

### ISSUE THREAD

**Issue by kirkness** [jwerre/node-canvas-lambda#2]
Hello! This is getting me a little closer to getting node-canvas running, however, I am running into `Fontconfig error: Cannot load default config file` now. Anyone else faced this or know if a fix?

**Comment by kirkness** [comment]
Fixed:
1: Create a `/fonts` directory in the service called 
2: Add the font file
3: Create a file within the fonts dir:
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <dir>/var/task/fonts/</dir>
  <cachedir>/tmp/fonts-cache/</cachedir>
  <config></config>
</fontconfig>
```
4: No longer need to call `registerFont`

**Comment by codemaster08240328** [comment]
Hi @kirkness , now I have same issue as you.
Can you explain me more detail how you fixed it?

**Comment by codemaster08240328** [comment]
where did you create a `fonts` directory exactly and which filename did you use for a new file?

**Comment by mihkelambre** [comment]
> where did you create a `fonts` directory exactly and which filename did you use for a new file?

didi you get the answer?

**Comment by victhevenot** [comment]
would also love additional information - running into the same issue!

**Comment by vatanuki** [comment]
by default its looking for fonts here
`/usr/share/fonts`

force it too look in your config:
`process.env.FONTCONFIG_PATH='./fonts';`

PS: you can also use this for debug
`process.env.FC_DEBUG = 0xffff;`

PPS: using DEBUG while fonts folder containg font config file will ends with **segmentation fault**
so i put config in project root dir and leave fonts in fonts folder and correct FONTCONFIG_PATH

**Comment by Militia21** [comment]
Can someone explain the process, because i made a file called arial.tff and it worked but now it's not working again.

**Comment by toxicant123** [comment]
it seems work: `apt install fontconfig`
link: https://github.com/altair-viz/altair_saver/issues/100
