### ISSUE TITLE
Fonts Don't Renender 

### ISSUE THREAD

**Issue by andrewaustin** [jwerre/node-canvas-lambda#3]
Hi @jwerre,

Have you had much success with fonts on Lambda? It seems like the fonts just render as boxes. When I had this problem with node-canvas on docker, I just did a `npm install canvas --rebuild-from-source` and this fixed the issue. (Unfortunately, when I build node-canvas inside amazonlinux on Docker I have to include a lot more shared libraries than the 3 that this layer requires).

**Comment by jwerre** [comment]
What version of Node.js are you using? I haven't had any problems with fonts using Node 10. Once gotcha with Canvas is you need to make sure you call `registerFont` before `createCanvas`.

**Comment by andrewaustin** [comment]
I'm not even using a using a custom font, just something simple on Node.js 10 on Lambda:

```
ctx.fillStyle = 'black';
ctx.font = 'bold 18px serif';
```

**Comment by eranmit99** [comment]
@andrewaustin  can u pls specify where did u place the font file ?

**Comment by andrewaustin** [comment]
> @andrewaustin can u pls specify where did u place the font file ?

I have this code:

`
function loadFont () {
  registerFont(path.join(__dirname, '..', 'fonts', 'Roboto-Bold.ttf'), { family: 'Roboto Bold' });
}
`

**Comment by jwerre** [comment]
I updated the layer and included two more libraries (libfontconfig.so.1, libpixman-1.so.0). Can you download the new layer and try it again. Let me know how it goes.
